<?php

/**
 * This class defines functions  to generate shortcode for location selected
 * @author Luca Bonaldo <info@lucabonaldo.it>
 * @package LB-Select-Location
 */
class Select_Shortcode {

  /**
   * This function constructor has add the actions for wordpress
   */
  public function __construct() {

    add_action('hook_script', array(&$this, 'print_script'), 10, 3);
    add_shortcode('lb-sl', array(&$this, 'get_shortcode'));
  }

  /**
   * This function create the code html  of shortcode for location selected
   * @param array $atts Attributes by shortcode
   * @return string Code Html generated by Shortcode
   */
  public function get_shortcode($atts) {

    extract(shortcode_atts(array(
        'form' => '1',
        'province' => 'nome',
        'comuni' => 'nome',
        'label_regioni' => 'Scegli ...',
        'label_province' => 'Scegli ...',
        'label_comuni' => 'Scegli ...',
        'label_wait' => 'Attendere ...',
        'text_regioni' => 'Regione',
        'text_province' => 'Provincia',
        'text_comuni' => 'Comune'
                    ), $atts));

    $form = trim($form);

    $province = trim($province);
    $comuni = trim($comuni);

//    echo '123<br>';
//    echo $province . "<br>" . $comuni . "<br><br>";

    $province = str_replace("&", "&provincia_", "provincia_" . $province);
    $province = str_replace("amp;", "", $province);

    $comuni = str_replace("&", "&comune_", "comune_" . $comuni);
    $comuni = str_replace("amp;", "", $comuni);

//    echo '456<br>';
    //   echo $province . "<br>" . $comuni . "<br><br>";

    $labels = array(
        'regioni' => trim($label_regioni),
        'province' => trim($label_province),
        'comuni' => trim($label_comuni),
        'wait' => trim($label_wait)
    );

    $queries = array(
        'province' => $province,
        'comuni' => $comuni
    );

    do_action('hook_script', $form, $labels, $queries);

    $html = '<div class="select-content">';
    $html.= $this->print_regioni($form, trim($text_regioni));
    $html.= $this->print_province($form, trim($text_province));
    $html.= $this->print_comuni($form, trim($text_comuni));
    $html.= '</div>';

    return $html;
  }

  /**
   * This function create the code html for tag select associated with regions
   * @global Select $select @see Select::$select
   * @param string $id_form Name associated with form tag that include it
   * @param string $label Label text for tag label
   * @return string Code Html generated for tag select associated with regions
   */
  private function print_regioni($id_form, $label) {

    global $select;

    $tmp = '<div>';
    $tmp.= '<select name="sl-regioni-' . $id_form . '" id="sl-regioni-' . $id_form . '">';
    $tmp.= '<option value="0"></option>';
    $tmp.= $select->display_regioni();
    $tmp.= '</select>';
    $tmp.= '<label for="sl-regioni-' . $id_form . '">' . $label . '</label>';
    $tmp.= '</div>';

    return $tmp;
  }

  /**
   * This function create the code html for tag select associated with provinces
   * @param string $id_form Name associated with form tag that include it
   * @param string $label Label text for tag label
   * @return string Code Html generated for tag select associated with provinces
   */
  private function print_province($id_form, $label) {

    $tmp = '<div>';
    $tmp.= '<select name="sl-province-' . $id_form . '" id="sl-province-' . $id_form . '">';
    $tmp.= '</select>';
    $tmp.= '<label for="sl-province-' . $id_form . '">' . $label . '</label>';
    $tmp.= '</div>';

    return $tmp;
  }

  /**
   * This function create the code html for tag select associated with longhouse
   * @param type $id_form Name associated with form tag that include it
   * @param string $label Label text for tag label
   * @return string Code Html generated for tag select associated with longhouse
   */
  private function print_comuni($id_form, $label) {

    $tmp = '<div>';
    $tmp.= '<select name="sl-comuni-' . $id_form . '" id="sl-comuni-' . $id_form . '">';
    $tmp.= '</select>';
    $tmp.= '<label for="sl-comuni-' . $id_form . '">' . $label . '</label>';
    $tmp.= '</div>';

    return $tmp;
  }

  /**
   * This function to print script javascript for call of sl_handler_ajax() @see select.js
   * @param string $id_form Name associated with form tag that include it
   * @param array $labels Thi array contains of attributes for labels the tags select  
   * @param array $queries This array Contains the type of column to selected into database
   */
  public function print_script($id_form, $labels, $queries) {
    ?>

    <input type="hidden" id="query-province-<?php echo $id_form ?>" value="<?php echo $queries['province'] ?>"/>
    <input type="hidden" id="query-comuni-<?php echo $id_form ?>" value="<?php echo $queries['comuni'] ?>"/>

    <script type="text/javascript">

      jQuery(document).ready(function($) {

        var id_form = '<?php echo $id_form ?>';
        var labels = {
    <?php $this->print_script_object($labels); ?>
        };
        var queries = {
    <?php $this->print_script_object($queries); ?>
        };
        //        console.log(id_form);
        //        console.log(queries);
        //        console.log(labels);
        sl_handler_ajax(id_form, labels, queries);
      });

    </script>
    <?php
  }

  /**
   * this function print attributes by object javascript  
   * @param array $array
   */
  private function print_script_object($array = array()) {

    for (reset($array), $i = 0, $dim = count($array); current($array); next($array), $i++) {
      echo key($array) . ' : "' . current($array) . '"';
      if ($i < $dim - 1)
        echo ',';
    }
  }

}

$select_shortcode = new Select_Shortcode();
?>